name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # roda todos os dias à meia-noite UTC
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Commit e Push do Snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "🌀 Atualizando animação da cobrinha"
          add: "dist/*.svg"
